defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: 我的前端猫

title: 我的前端猫
description: 我的前端猫
url: "http://tmallfe.github.io"

author:
  name: 我的前端猫
  email: join-tmallfe@list.alibaba-inc.com
  github: tmallfe
  bio: keep calm and carry on!

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

BASE_PATH:

markdown: kramdown
